---

- name: Ubuntu | Install prerequisites
  raw: sleep 10 &&  apt-get update -qq &&  apt-get install -qq -y python2.7

- name: Ubuntu | Configure defaults
  raw:  update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  tags:
    - update-alternatives
